import Link from 'next/link'

export default function Intro() {
    return (
    <div id="intro-box" className="instructions-stim-container">
      <div className="row">
        <div className="col d-flex justify-content-center">
          <h2 className="bolded-blue">ReproNLP Definitions Accuracy</h2>
        </div>
      </div>
      <div className="row">
        <div className="col text-wrap justify-content-center align-self-center" >
            <p style={{padding: '20px'}}>
                <span>The aim of the project is to evaluate the factual accuracy of scientific definitions that were
generated by a computer system. This experiment sits within the broader context of the
ReproHum project, where we are comparing different types of evaluation to see which is best.</span>
            </p>
        </div>
      </div>
      <div className="row">
        <div className="col d-flex justify-content-center">
          <Link href="/informed-consent">
            <button type="button" className="btn btn-outline-primary btn-lg">Continue</button>
          </Link>
        </div>
      </div>
    </div>
    );
    }
